### ISSUE TITLE
Stoppit and Tidyup

### ISSUE THREAD

**Issue by iaindillingham** [opensafely/gh-testing-research#4]
This repo is used by opensafely-core/research-action for testing. It should:

- [ ] be added to the Researcher Experience Team's list of repos
- [x] have a clear README.md
- [x] have a dataset definition (ehrQL) rather than a study definition (cohort-extractor)
- [x] have `main` rather than `master`
- [x] have branch protection rules

As the study within this repo is also a dependency of opensafely-core/research-action, then the study should be tested on a schedule to ensure that any changes to `opensafely` (i.e. the CLI) don't break it.

![Stoppit and Tidyup](https://upload.wikimedia.org/wikipedia/en/e/e9/StopItTidyUp.JPG)

**Comment by remlapmot** [comment]
For testing on a schedule - (you probably already know) - GHA workflows allow a CRON-type syntax.

In [cox-ipw](https://github.com/opensafely-actions/cox-ipw) we run our little test once a week with

```yaml
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '37 2 * * TUE' 
```

https://github.com/opensafely-actions/cox-ipw/blob/6d53340cb9a56da72991ee87d756dfc63e37eceb/.github/workflows/test_runner.yaml#L6-L7

(I don't know if there is a cleverer way to do it based on checking for new releases of the CLI)
